In [ ]:
import numpy as np

a = np.array([12, 8, 20, 17, 15])
print(a)

a.sort()
print(a)

print(a.shape)
print(type(a))
print(a.T.shape)

[12  8 20 17 15]
[ 8 12 15 17 20]
(5,)
<class 'numpy.ndarray'>
(5,)


In [ ]:
import numpy as np

b = np.array([[12, 3, 4.], [1, 4, 5]])

print(b)
print(b.ndim)

print(b.shape)
print(b.dtype)

print(b.T.shape)

[[12.  3.  4.]
 [ 1.  4.  5.]]
2
(2, 3)
float64
(3, 2)
2


In [ ]:
import numpy as np

c = np.array([[[1, 3, 0, 1], [1, 1, 4, 2], [3, 3, 4, 1]],\
              [[2, 1, 2, 1], [1, 0, 1, 0], [1, 5, 6, 2]]])

print(c)

print(c.ndim)
print(c.shape)
print(c.dtype)

print(c.T)
print(c.T.shape)

[[[1 3 0 1]
  [1 1 4 2]
  [3 3 4 1]]

 [[2 1 2 1]
  [1 0 1 0]
  [1 5 6 2]]]
3
(2, 3, 4)
int64
[[[1 2]
  [1 1]
  [3 1]]

 [[3 1]
  [1 0]
  [3 5]]

 [[0 2]
  [4 1]
  [4 6]]

 [[1 1]
  [2 0]
  [1 2]]]
(4, 3, 2)


In [ ]:
import numpy as np

d = np.zeros([2, 3])
print(d)
print(d.dtype)

d = np.ones([3, 2])
print(d)
print(d.dtype)

e = np.random.random([2, 5])
print(e)
print(e.shape)
print(e.T.shape)

f = np.arange(1, 20, 2.5)
print(f)
print(f.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[0.49050008 0.19889894 0.80747371 0.64460289 0.27299006]
 [0.47474767 0.16831556 0.35256523 0.24724339 0.14063128]]
(2, 5)
(5, 2)
[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5]
(8,)


In [ ]:
import tensorflow.keras.datasets as ds

(x_train, y_train), (x_test, y_test) = ds.cifar10.load_data()
print(x_train)

print(x_train.shape)
print(x_train.dtype)
print(x_train.nbytes)

print(x_train.size*x_train.itemsize)
print(np.prod(x_train.shape)*x_train.itemsize)

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [ ]:
x = 10
y = x
y = 12

print(x, y)

10 12


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = a
b[0] = -10
print(a, b)

c = a.copy()
c[1] = -20
print(a, c)

[-10  20  30  40] [-10  20  30  40]
[-10  20  30  40] [-10 -20  30  40]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape([2, 3])
print(a)
print(b)
a[4] = -5
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 -5  6]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.T
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import tensorflow.keras.datasets as ds

(x_train, y_train), (x_test, y_test) = ds.cifar10.load_data()
print(x_train.shape)
print(x_train.T.shape)
print(x_train.swapaxes(2, 3).shape)
print(x_train.transpose(1, 2, 3, 0).shape)

(50000, 32, 32, 3)
(3, 32, 32, 50000)
(50000, 32, 3, 32)
(32, 32, 3, 50000)


In [ ]:
import numpy as np
import time

a = np.array([[3, 2, -2, 0, 1], [2, -3, 4, 5, 2], [1, 1, 2, -3, 2]])
print(a)
print(a[2, 1], a[-1, 3], a[0, -2])

print(a[2])
print(a[-2])
print(a[:, 3])

print(a[1, 1:3])
print(a[:, 1:])
print(a[:, :3])

print(a[1, 3], a[1][3])

start = time.time()
print(a[1, 3])
end = time.time()
print(end - start)

start = time.time()
print(a[1][3])
end = time.time()
print(end - start)

print(a[:, 2], a[:][2])


[[ 3  2 -2  0  1]
 [ 2 -3  4  5  2]
 [ 1  1  2 -3  2]]
1 -3 0
[ 1  1  2 -3  2]
[ 2 -3  4  5  2]
[ 0  5 -3]
[-3  4]
[[ 2 -2  0  1]
 [-3  4  5  2]
 [ 1  2 -3  2]]
[[ 3  2 -2]
 [ 2 -3  4]
 [ 1  1  2]]
5 5
5
0.00013399124145507812
5
0.00013828277587890625
[-2  4  2] [ 1  1  2 -3  2]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([0, -1, 2, 6, 1])

print(3*a)
print(a**2)

print(a+b)
print(a-b)

print(a*b)
print(a/b)

print(b < 0)

[ 3  6  9 12 15]
[ 1  4  9 16 25]
[ 1  1  5 10  6]
[ 1  3  1 -2  4]
[ 0 -2  6 24  5]
[        inf -2.          1.5         0.66666667  5.        ]
[False  True False False False]


<ipython-input-84-9b39b95856a8>:13: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [ ]:
import numpy as np

a = np.array([[3, 2, -2, 0, 1], [2, -3, 4, 5, 2], [0, 1, -2, -3, 2]])
print(a)

print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.cumsum(axis=0))
print(a.cumsum(axis=1))

print(a.max(axis=0))
print(a.max(axis=1))

print(a.argmax(axis=0))
print(a.argmax(axis=1))

[[ 3  2 -2  0  1]
 [ 2 -3  4  5  2]
 [ 0  1 -2 -3  2]]
12
[5 0 0 2 5]
[ 4 10 -2]
[[ 3  2 -2  0  1]
 [ 5 -1  2  5  3]
 [ 5  0  0  2  5]]
[[ 3  5  3  3  4]
 [ 2 -1  3  8 10]
 [ 0  1 -1 -4 -2]]
[3 2 4 5 2]
[3 5 2]
[0 0 1 1 1]
[0 3 4]


In [ ]:
import numpy as np

a = np.array([[3, 2, -2, 0, 1], [2, -3, 4, 5, 2], [0, 1, -2, -3, 2]])
positive = a > 0
print(positive)
b = a[positive]
print(b)
print(b.sum())

print(a[a>0].sum())

[[ True  True False False  True]
 [ True False  True  True  True]
 [False  True False False  True]]
[3 2 1 2 4 5 2 1 2]
22
22


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[7, 8, 9], [1, 4, 7]])
x = np.vstack([a, b])
print(x)

y = np.vstack([a, c])
print(y)

z = np.hstack([a, b])
print(z)

zz = np.hstack([a, c])


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [1 4 7]]
[1 2 3 4 5 6]


ValueError: ignored

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0, -1, 2, 6, 1])
c = np.array([np.pi/2, np.pi, np.pi*2])
print(c)
print(np.add(a, b))

print(np.log10(a))
print(np.sin(c))

print(np.left_shift(a, 1))
print(np.greater(a, b))

print(np.maximum(a, b))
print(c.round(2))

[1.57079633 3.14159265 6.28318531]
[ 1  1  5 10  6]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[ 1.0000000e+00  1.2246468e-16 -2.4492936e-16]
[ 2  4  6  8 10]
[ True  True  True False  True]
[1 2 3 6 5]
[1.57 3.14 6.28]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4], [0, 1, 2, 3], [-1, 0, 1, 2]])
b = np.array([[1, 1, 2, 2]])
print(a+b)

[[2 3 5 6]
 [1 2 4 5]
 [0 1 3 4]]


In [ ]:
import numpy as np

a = np.array([[4, 2], [2, 7], [-2, 1]])
c = np.array([[1, -2, 3], [5, 0, 2]])
res = np.matmul(a, c)
print(res)

[[14 -8 16]
 [37 -4 20]
 [ 3  4 -4]]


In [ ]:
a = [5, 2, 3, 8, 2]
b = (5, 2, 3, 8, 2)
c = {1:'book',  5:'notebook', 3:'pencil', -3:'eraser', 'as':120, 12.2:50}
d = set([5, 2, 3, 8, 2])  #set은 print 때 중복 된 수 print X
print(type(a), type(b), type(c), type(d))

print(a, b, c, d, sep='\n')
b[2] = -3

<class 'list'> <class 'tuple'> <class 'dict'> <class 'set'>
[5, 2, 3, 8, 2]
(5, 2, 3, 8, 2)
{1: 'book', 5: 'notebook', 3: 'pencil', -3: 'eraser', 'as': 120, 12.2: 50}
{8, 2, 3, 5}


TypeError: ignored

In [ ]:
a = [5, 2, 3, ['pencil', 4, -2, 2], 'book']
c = {1:'book',  5:'notebook', 3:'pencil', -3:'eraser', 'as':120, 12.2:50}
print(a[2], a[3], a[4])
print(a[3][2], a[4][1])

print(a[1:4], a[:-1], a[2:], sep='\n')
print(a[3][1:], a[4][:3])

print(c[-3], c[5], c['as'], c[12.2])
print(c[2])

3 ['pencil', 4, -2, 2] book
-2 o
[2, 3, ['pencil', 4, -2, 2]]
[5, 2, 3, ['pencil', 4, -2, 2]]
[3, ['pencil', 4, -2, 2], 'book']
[4, -2, 2] boo
eraser notebook 120 50


KeyError: ignored

In [2]:
x = [1, 2, 'pen']
y = [-2, 1]
print(3*x)
print(y+x)

[1, 2, 'pen', 1, 2, 'pen', 1, 2, 'pen']
[-2, 1, 1, 2, 'pen']


In [4]:
z = [1, 2, 3, 4]
z.append(-7)
print(z)

z.insert(1, -7)
print(z)

z.remove(-7)
print(z)

v = z.pop(2)
print(v, z)

[1, 2, 3, 4, -7]
[1, -7, 2, 3, 4, -7]
[1, 2, 3, 4, -7]
3 [1, 2, 4, -7]


In [7]:
x2 = [i*i for i in range(10)]
print(x2)

x2 = []
for i in range(10):
  x2.append(i*i)
print(x2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [9]:
x3 = [[i,j*2] for i in [10, 2, 3, 1] for j in [2, 4]]
print(x3)

x4 = [[i, j*2] for i in [10, 2, 3, 1] for j in [2, 4] if i != j]
print(x4)

[[10, 4], [10, 8], [2, 4], [2, 8], [3, 4], [3, 8], [1, 4], [1, 8]]
[[10, 4], [10, 8], [2, 8], [3, 4], [3, 8], [1, 4], [1, 8]]
