In [ ]:
import numpy as np

a = np.arange(12).reshape(3, -1)
print(len(a[0]))

4


In [8]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

digit = datasets.load_digits()

X_train, X_test, Y_train, Y_test = train_test_split(digit.data, digit.target, train_size=0.6, random_state = 21)

s = svm.SVC(gamma=0.001)
s.fit(X_train, Y_train)

res = s.predict(X_test)

conf = np.zeros((10, 10))

for i in range(len(res)):
  conf[res[i]][Y_test[i]] += 1
print(conf)

no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("ACCURACY >> ", accuracy*100, "%")

[[71.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 73.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0. 62.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 76.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. 62.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. 79.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. 71.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 80.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 71.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0. 67.]]
ACCURACY >>  99.02642559109874 %
