In [ ]:
from sklearn.linear_model import Perceptron

#훈련 집합 구축 #OR gate
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
Y = [-1, 1, 1, 1]

p = Perceptron()
p.fit(X, Y)


print('Parameter of Perceptron >>', p.coef_, p.intercept_)
print('Prediction >>', p.predict(X))
print('Accuracy >>', p.score(X, Y)*100, '%')

Parameter of Perceptron >> [[2. 2.]] [-1.]
Prediction >> [-1  1  1  1]
Accuracy >> 100.0 %


In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split \
 (digit.data, digit.target, train_size=.6, random_state=444)

p = Perceptron(max_iter=100, eta0=.001, verbose=0)
p.fit(x_train, y_train)

res = p.predict(x_test)

conf = np.zeros((10, 10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
accuracy = correct/len(res)
print('Accuracy >>', accuracy*100, '%')

[[68.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 80.  2.  0.  2.  1.  2.  1. 10.  2.]
 [ 0.  0. 65.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0. 74.  0.  3.  0.  0.  6.  1.]
 [ 0.  1.  0.  0. 62.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 73.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0. 68.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 59.  0.  0.]
 [ 0.  0.  1.  2.  1.  1.  2.  0. 56.  1.]
 [ 0.  0.  0.  1.  0.  3.  0.  0.  1. 65.]]
Accuracy >> 93.18497913769124 %


In [ ]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np

digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split \
 (digit.data, digit.target, train_size=.6, random_state=9999)

mlp = MLPClassifier(hidden_layer_sizes=100, learning_rate_init=.001, \
                    batch_size=32, max_iter=300, solver='sgd', verbose=True)

mlp.fit(x_train, y_train)

res = mlp.predict(x_test)

conf = np.zeros((10, 10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
print('Accuracy >>', (correct/len(res))*100, '%')

Iteration 1, loss = 1.44166892
Iteration 2, loss = 0.19984638
Iteration 3, loss = 0.13569237
Iteration 4, loss = 0.10111958
Iteration 5, loss = 0.08655595
Iteration 6, loss = 0.07110236
Iteration 7, loss = 0.06431584
Iteration 8, loss = 0.05838456
Iteration 9, loss = 0.04831709
Iteration 10, loss = 0.04713001
Iteration 11, loss = 0.04237752
Iteration 12, loss = 0.03894881
Iteration 13, loss = 0.03614085
Iteration 14, loss = 0.03340013
Iteration 15, loss = 0.03094823
Iteration 16, loss = 0.02900430
Iteration 17, loss = 0.02681160
Iteration 18, loss = 0.02502337
Iteration 19, loss = 0.02381591
Iteration 20, loss = 0.02291090
Iteration 21, loss = 0.02133615
Iteration 22, loss = 0.02079769
Iteration 23, loss = 0.02007130
Iteration 24, loss = 0.01929446
Iteration 25, loss = 0.01787644
Iteration 26, loss = 0.01790766
Iteration 27, loss = 0.01729800
Iteration 28, loss = 0.01592355
Iteration 29, loss = 0.01519048
Iteration 30, loss = 0.01514776
Iteration 31, loss = 0.01493301
Iteration 32, los

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import numpy as np

mnist = fetch_openml('mnist_784')
mnist.data = mnist.data/255.
x_train = mnist.data[:60000]; x_test = mnist.data[60000:]
y_train = np.int16(mnist.target[:60000]); y_test = np.int16(mnist.target[60000:])

mlp = MLPClassifier(hidden_layer_sizes=(100), learning_rate_init=.001, \
                    batch_size=512, max_iter=300, solver='adam', verbose=True)

mlp.fit(x_train, y_train)

res = mlp.predict(x_test)

conf = np.zeros((10, 10), dtype=np.int16)
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
print('Accuracy >>', (correct/len(res)) * 100, '%')


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Iteration 1, loss = 0.63719504
Iteration 2, loss = 0.27972256
Iteration 3, loss = 0.22741888
Iteration 4, loss = 0.19086687
Iteration 5, loss = 0.16555559
Iteration 6, loss = 0.14556290
Iteration 7, loss = 0.12962131
Iteration 8, loss = 0.11532342
Iteration 9, loss = 0.10352232
Iteration 10, loss = 0.09224451
Iteration 11, loss = 0.08369695
Iteration 12, loss = 0.07623403
Iteration 13, loss = 0.06963658
Iteration 14, loss = 0.06351488
Iteration 15, loss = 0.05882537
Iteration 16, loss = 0.05425346
Iteration 17, loss = 0.04991043
Iteration 18, loss = 0.04643163
Iteration 19, loss = 0.04330623
Iteration 20, loss = 0.04047854
Iteration 21, loss = 0.03765374
Iteration 22, loss = 0.03476088
Iteration 23, loss = 0.03283884
Iteration 24, loss = 0.03019193
Iteration 25, loss = 0.02763135
Iteration 26, loss = 0.02599609
Iteration 27, loss = 0.02439141
Iteration 28, loss = 0.02269682
Iteration 29, loss = 0.02124505
Iteration 30, loss = 0.01991701
Iteration 31, loss = 0.01854310
Iteration 32, los

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np

mnist = fetch_openml('mnist_784')
mnist.data = mnist.data/255.
x_train = mnist.data[:60000]; x_test = mnist.data[60000:]
y_train = np.int16(mnist.target[:60000]); y_test = np.int16(mnist.target[60000:])

svm = SVC(gamma=.0001, C=.7, verbose=True, max_iter=300, random_state=777)

svm.fit(x_train, y_train)

res = svm.predict(x_test)

conf = np.zeros((10, 10), dtype=np.int16)
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
print('Accuracy >>', (correct/len(res)) * 100, '%')


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


[LibSVM]

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=300).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


[[606   0   1   0   1   1   1   0   0   0]
 [  0 164   8   0   0   0   0   0   0   0]
 [ 13   0 234   2   0   0  13   0   2   1]
 [  3   1  14 222   0   1   0   0   2   0]
 [  1   0   8   0 254   1  10   2   1   8]
 [169   0  23  16   3 144   8   0   7   5]
 [ 43   0  91  12   6  11 616   0   5   1]
 [ 19   0  20   2  36   3   6 239   2  36]
 [ 48 150 286  95  20 105  34   4 179   7]
 [ 78 820 347 661 662 626 270 783 776 951]]
Accuracy >> 36.09 %
